version: '3.4'

services:
  crowdsourcingayat:
    image: crowdsourcingayat
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - logging-data:/src/log_files
    networks:
      - backend

volumes:
  logging-data:

networks:
  backend:
