version: '3.4'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO-ACCESS-KEY} 
      MINIO_ROOT_PASSWORD: ${MINIO-SECRET-KEY}
    command: server --console-address ":9001" /data
    networks:
      - backend

  crowdsourcingayat:
    image: crowdsourcingayat
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - minio
    volumes:
      - logging-data:/app/src/log_files
    networks:
      - backend

volumes:
  minio-storage: {}
  logging-data:

networks:
  backend:
