version: '3.4'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: 8ROxKE3xQEG0NMFO
      MINIO_ROOT_PASSWORD: K3BiXrCKwzweKS6er5hRyAIU4cxn7N60
    command: server --console-address ":9001" /data
    networks:
      - backend

  crowdsourcingayat:
    image: crowdsourcingayat
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - minio
    volumes:
      - logging-data:/src/log_files
    networks:
      - backend

volumes:
  minio-storage: {}
  logging-data:

networks:
  backend:
